version: '3'

services:
  jequi:
    image: jequi
    ports:
      - "7878:7878"
    volumes:
      - ./jequi_go.so:/etc/jequi/jequi_go.so
      - ./etc/jequi/conf.yaml:/etc/jequi/conf.yaml
  jequi-go:
    image: jequi-go
    ports:
      - "7879:7878"
    volumes:
      - ./plugins/jequi_go/go/handle:/etc/jequi/plugins/jequi_go/go/handle
      - ./etc/jequi/conf.yaml:/etc/jequi/conf.yaml
