// generated by generate.go; DO NOT EDIT

package main

import (
	handler "github.com/handle"
	"github.com/jequi_go"
)

func handleRequest(req jequi_go.Request, resp jequi_go.Response) {
	handler.HandleRequest(req, resp)
}
